source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.9', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'sinatra-flash'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
